# chunhui2001/alpine:graalvm-19.3.2
# Version 0.0.1
FROM alpine:3.12.0
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"


WORKDIR /root

# docker build -f Dockerfile . -t 'chunhui2001/alpine:graalvm-19.3.2'
# docker run -dit --entrypoint="top" -P --name alpine.graalvm-19.3.2 chunhui2001/alpine:graalvm-19.3.2
# docker run -dit -p 8080:8080 --name alpine.graalvm-19.3.2 chunhui2001/alpine:graalvm-19.3.2
# docker push chunhui2001/alpine:graalvm-19.3.2
# docker pull chunhui2001/alpine:graalvm-19.3.2


