
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  regnet.node1:                
    container_name: regnet.node1
    image: chunhui2001/alpine:3.12.regnet
    hostname: regnet.node1
    ##mem_limit: 100m
    entrypoint: ["/bin/sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.15



