## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  nginx_1.18.0:
    container_name: nginx_1.18.0
    image: chunhui2001/alpine:3.12.nginx
    mem_limit: 100m
    ports:
      - 8008:80
      #- 18443:18443
    #entrypoint: ["/docker-entrypoint.sh"]
    volumes:
      #- ./ssl:/usr/local/nginx/ssl:ro
      # 在 centos7 下需执行: chcon -Rt svirt_sandbox_file_t config/
      - ./conf/nginx.sample.nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/index.html:/www/index.html:ro
      - ./conf/404.html:/var/lib/nginx/html/404.html:ro
      - ./conf/50x.html:/var/lib/nginx/html/50x.html:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.61
