
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  redis_single:                
    container_name: redis_single
    image: chunhui2001/alpine:3.10.redis-5.0.5
    hostname: redis.single
    mem_limit: 100m
    ports:
      - 6479:6379
    entrypoint: ["entrypoint.sh"]
    command: ["redis-server", "/etc/redis.conf"]
    volumes:
      - ./conf/redis.single.conf:/etc/redis.conf:ro
    restart: always
    networks:
        br0:
          ipv4_address: 172.16.197.15



