# chunhui2001/alpine:3.9.Tomcat-9.0.56
# Version 0.0.1
FROM chunhui2001/alpine:3.9.oraclejdk9
MAINTAINER Chunhui.Zhang "chunhui2001@gmail.com"

COPY apache-tomcat-9.0.56.tar.gz /usr/local/
RUN tar -zxvf /usr/local/apache-tomcat-9.0.56.tar.gz -C /usr/local/ && ln -s apache-tomcat-9.0.56 /usr/local/tomcat

ENV CURL_VERSION 7.50.1
ENV LANG=C.UTF-8

ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH
RUN mkdir -p "$CATALINA_HOME"
WORKDIR $CATALINA_HOME

# let "Tomcat Native" live somewhere isolated
ENV TOMCAT_NATIVE_LIBDIR $CATALINA_HOME/native-jni-lib
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$TOMCAT_NATIVE_LIBDIR

ENV TOMCAT_MAJOR 9
ENV TOMCAT_VERSION 9.0.56
ENV TOMCAT_SHA512 7a02a8e0b12eea2e0bf1175d754bd19dc445e7182c2db033ba6ca1330161cc74207c9b9b7f0fce510417ece28f26cc36816b34eb394b0d27350631e64204aed3

RUN set -eux; \
    \
    apk add --no-cache --virtual .fetch-deps \
        gnupg \
        \
        ca-certificates \
        openssl \
    ; \
    \
    mkdir -p /tmp/nativeBuildDir && \
    tar -xvf $CATALINA_HOME/bin/tomcat-native.tar.gz -C /tmp/nativeBuildDir --strip-components=1; \
    \
    apk add --no-cache --virtual .native-build-deps build-base \
        apr-dev coreutils dpkg-dev dpkg gcc libc-dev make openssl-dev && \
    \
    cd /tmp/nativeBuildDir/native  && \
    ./configure --build=x86_64-linux-musl --libdir="$TOMCAT_NATIVE_LIBDIR" \
                --prefix="$CATALINA_HOME" --with-apr="$(which apr-1-config)" \
                --with-java-home="/usr/local/java" --with-ssl=yes && \
    make -j "$(nproc)" && make install && rm -rf /tmp/nativeBuildDir && \
    \
    rm -rf $CATALINA_HOME/bin/tomcat-native.tar.gz; \
    runDeps="$( scanelf --needed --nobanner --format '%n#p' --recursive "$TOMCAT_NATIVE_LIBDIR" | tr ',' '\n' | sort -u | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' )"; \
    apk add --virtual .tomcat-native-rundeps $runDeps; \
    apk del .fetch-deps .native-build-deps; \
    apk add --no-cache bash; \
    find $CATALINA_HOME/bin/ -name '*.sh' -exec sed -ri 's|^#!/bin/sh$|#!/usr/bin/env bash|' '{}' +

# verify Tomcat Native is working properly
RUN set -e \
    && nativeLines="$(catalina.sh configtest 2>&1)" \
    && nativeLines="$(echo "$nativeLines" | grep 'Apache Tomcat Native')" \
    && nativeLines="$(echo "$nativeLines" | sort -u)" \
    && echo >&2 "$nativeLines";

WORKDIR $CATALINA_HOME
EXPOSE 8080
CMD ["catalina.sh", "run"]

# docker build -f Dockerfile-Tomcat9.0.56 . -t 'chunhui2001/alpine:3.9.Tomcat-9.0.56'
# docker run -dit --entrypoint="top" -P --name alpine.Tomcat-9.0.56 chunhui2001/alpine:3.9.Tomcat-9.0.56
# docker run -dit -p 8181:8080 --name alpine.Tomcat-9.0.56 chunhui2001/alpine:3.9.Tomcat-9.0.56
# docker push chunhui2001/alpine:3.9.Tomcat-9.0.56
# docker pull chunhui2001/alpine:3.9.Tomcat-9.0.56


