
## 安装Docker Compose
# curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
# chmod +x /usr/local/bin/docker-compose
# docker-compose --version
# docker-compose up -d

version: '2.4'

networks:
    br0:
      external: true

services:
  redis7.2.3:                
    container_name: redis7.2.3
    image: chunhui2001/alpine:3.19.redis-7.2.3
    hostname: redis7.2.3
    mem_limit: 100m
    ports:
      - 6579:6379
    #entrypoint: ["/bin/sh", "-c", "while true; do echo 1 >/dev/null 2>/dev/null; sleep 1; done"]
    #command: []
    entrypoint: ["entrypoint.sh"]
    command: ["redis-server", "/etc/redis.conf"]
    volumes:
      - ./conf/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
      - ./conf/redis.conf:/etc/redis.conf:ro
    restart: always
    networks:
      br0:
        ipv4_address: 172.16.197.115



